export const ACTION_TYPES = {
    //USER SECTION
    SET_USER_STATE: 'SET_USER_STATE',

    SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

    SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

    SIGN_OUT_REQUEST: 'SIGN_OUT_REQUEST',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',

    SET_AUTH_DATA: 'SET_AUTH_DATA',
    REMOVE_AUTH_ERROR_AND_LOADING: 'REMOVE_AUTH_ERROR_AND_LOADING',

    SET_USER: 'SET_USER',
    GET_USER: 'GET_USER',
    REMOVE_USER: 'REMOVE_USER',

    //THEME SECTION
    SET_MODE_THEME: 'SET_MODE_THEME',

    //TODO SECTION
    SET_FILTER: 'SET_FILTER',
    RESET_TODOS: 'RESET_TODOS',
    REORDER_TODOS: 'REORDER_TODOS',
    CHANGE_TODO_IS_EDIT: 'CHANGE_TODO_IS_EDIT',
    CLOSE_ALL_TODOS_IS_EDIT: 'CLOSE_ALL_TODOS_IS_EDIT',

    GET_USER_REQUEST: 'GET_USER_REQUEST',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_FAILURE: 'GET_USER_FAILURE',

    GET_TODOS_REQUEST: 'GET_TODOS_REQUEST',
    GET_TODOS_SUCCESS: 'GET_TODOS_SUCCESS',
    GET_TODOS_FAILURE: 'GET_TODOS_FAILURE',

    REORDER_TODOS_REQUEST: 'REORDER_TODOS_REQUEST',
    REORDER_TODOS_SUCCESS: 'REORDER_TODOS_SUCCESS',
    REORDER_TODOS_FAILURE: 'REORDER_TODOS_FAILURE',

    ADD_TODO_REQUEST: 'ADD_TODO_REQUEST',
    ADD_TODO_SUCCESS: 'ADD_TODO_SUCCESS',
    ADD_TODO_FAILURE: 'ADD_TODO_FAILURE',

    REMOVE_TODO_REQUEST: 'REMOVE_TODO_REQUEST',
    REMOVE_TODO_SUCCESS: 'REMOVE_TODO_SUCCESS',
    REMOVE_TODO_FAILURE: 'REMOVE_TODO_FAILURE',

    UPDATE_TODO_REQUEST: 'UPDATE_TODO_REQUEST',
    UPDATE_TODO_SUCCESS: 'UPDATE_TODO_SUCCESS',
    UPDATE_TODO_FAILURE: 'UPDATE_TODO_FAILURE',
} as const

export type ActionType = (typeof ACTION_TYPES)[keyof typeof ACTION_TYPES]
