export const ACTION_TYPES = {
    SET_STATE: 'SET_STATE',
    ADD_TODO: 'ADD_TODO',
    REMOVE_TODO: 'REMOVE_TODO',
    REMOVE_ALL_TODOS: 'REMOVE_ALL_TODOS',
    CHANGE_TODO_STATUS: 'CHANGE_TODO_STATUS',
    CHANGE_TODO_IS_EDIT: 'CHANGE_TODO_IS_EDIT',
    CLOSE_ALL_TODOS_IS_EDIT: 'CLOSE_ALL_TODOS_IS_EDIT',
    EDIT_TODO_CONTEXT: 'EDIT_TODO_CONTEXT',
} as const

export type ActionType = (typeof ACTION_TYPES)[keyof typeof ACTION_TYPES]
