export const ACTION_TYPES = {
    SET_FILTER: 'SET_FILTER',

    // SET_TODO_STATE: 'SET_TODO_STATE',
    SET_USER_STATE: 'SET_USER_STATE',

    RESET_TODOS: 'RESET_TODOS',

    // CHANGE_TODO_COUNTER: 'CHANGE_TODO_COUNTER',
    // CHANGE_TODO_IS_EDIT: 'CHANGE_TODO_IS_EDIT',
    // CLOSE_ALL_TODOS_IS_EDIT: 'CLOSE_ALL_TODOS_IS_EDIT',
    // FILTER_TODOS: 'FILTER_TODOS',
    // REORDER_TODOS: 'REORDER_TODOS',
    // RESET_TODO_STATE: 'RESET_TODO_STATE',

    // SET_PAGINATION_PAGE: 'SET_PAGINATION_PAGE',
    // SET_IS_END_TODOS: 'SET_IS_END_TODOS',

    SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

    SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

    SIGN_OUT_REQUEST: 'SIGN_OUT_REQUEST',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',

    SET_AUTH_DATA: 'SET_AUTH_DATA',
    REMOVE_AUTH_ERROR_AND_LOADING: 'REMOVE_AUTH_ERROR_AND_LOADING',

    SET_USER: 'SET_USER',
    GET_USER: 'GET_USER',
    REMOVE_USER: 'REMOVE_USER',

    GET_USER_REQUEST: 'GET_USER_REQUEST',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_FAILURE: 'GET_USER_FAILURE',

    GET_TODOS_REQUEST: 'GET_TODOS_REQUEST',
    GET_TODOS_SUCCESS: 'GET_TODOS_SUCCESS',
    GET_TODOS_FAILURE: 'GET_TODOS_FAILURE',

    ADD_TODO_REQUEST: 'ADD_TODO_REQUEST',
    ADD_TODO_SUCCESS: 'ADD_TODO_SUCCESS',
    ADD_TODO_FAILURE: 'ADD_TODO_FAILURE',

    REMOVE_TODO_REQUEST: 'REMOVE_TODO_REQUEST',
    REMOVE_TODO_SUCCESS: 'REMOVE_TODO_SUCCESS',
    REMOVE_TODO_FAILURE: 'REMOVE_TODO_FAILURE',
} as const

export type ActionType = (typeof ACTION_TYPES)[keyof typeof ACTION_TYPES]

export const ASYNC_ACTION_TYPES = {
    // ASYNC_SET_TODOS: 'ASYNC_SET_TODOS',
    // ASYNC_GET_TODOS: 'ASYNC_GET_TODOS',
    // ASYNC_ADD_TODO: 'ASYNC_ADD_TODO',
    // ASYNC_REMOVE_TODO: 'ASYNC_REMOVE_TODO',
    // ASYNC_EDIT_TODO: 'ASYNC_EDIT_TODO',
    // ASYNC_CHANGE_TODO_STATUS: 'ASYNC_CHANGE_TODO_STATUS',
    // ASYNC_REMOVE_ALL_TODOS: 'ASYNC_REMOVE_ALL_TODOS',
    // ASYNC_SET_LOADING_TODOS: 'ASYNC_SET_LOADING_TODOS',
} as const

export type AsyncActionType = (typeof ACTION_TYPES)[keyof typeof ACTION_TYPES]
