export const ACTION_TYPES = {
    SET_STATE: 'SET_STATE',
    RESET_STATE: 'RESET_STATE',
    ADD_TODO: 'ADD_TODO',
    REMOVE_TODO: 'REMOVE_TODO',
    REMOVE_ALL_TODOS: 'REMOVE_ALL_TODOS',
    CHANGE_TODO_STATUS: 'CHANGE_TODO_STATUS',
    CHANGE_TODO_IS_EDIT: 'CHANGE_TODO_IS_EDIT',
    CLOSE_ALL_TODOS_IS_EDIT: 'CLOSE_ALL_TODOS_IS_EDIT',
    EDIT_TODO_CONTEXT: 'EDIT_TODO_CONTEXT',
    FILTER_TODOS: 'FILTER_TODOS',

    SET_TOKEN: 'SET_TOKEN',

    SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

    SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

    SIGN_OUT_REQUEST: 'SIGN_OUT_REQUEST',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',

    SET_AUTH_DATA: 'SET_AUTH_DATA',
    REMOVE_AUTH_ERROR_AND_LOADING: 'REMOVE_AUTH_ERROR_AND_LOADING',
} as const

export type ActionType = (typeof ACTION_TYPES)[keyof typeof ACTION_TYPES]

export const ASYNC_ACTION_TYPES = {
    ASYNC_ADD_TODO: 'ASYNC_ADD_TODO',
    ASYNC_REMOVE_TODO: 'ASYNC_REMOVE_TODO',
    ASYNC_EDIT_TODO_CONTEXT: 'ASYNC_EDIT_TODO_CONTEXT',
    ASYNC_REMOVE_ALL_TODOS: 'ASYNC_REMOVE_ALL_TODOS',
} as const

export type AsyncActionType = (typeof ACTION_TYPES)[keyof typeof ACTION_TYPES]
